framework:
  github: amirfaramarzi/tower
  version: 1.17

build_deps:
  - libevent-dev
  - libssl-dev

php_mod:
  - pcntl
  - sockets

php_ext:
  - event
  - redis

before_command:
  - mkdir storage/logs -p

command: php server.php start
