framework:
  github: chubbyphp/chubbyphp-framework
  version: 4.0

build_deps:
  - libevent-dev
  - libssl-dev

php_mod:
  - pcntl
  - sockets

php_ext:
  - event

command: php public/index.php start
